package org.paquitosoft.lml.model.exception;

/**
 *  This exception is used when user request database to create primary keys for his 
 *  entities, and database does not return that generated keys after inserting the entity
 * 
 * @author paquitosoft
 */
public class AutogeneratedKeysReturnNotSupportedException extends InternalErrorException {

    public AutogeneratedKeysReturnNotSupportedException(String message, Throwable t) {
        super(message, t);
    }

    public AutogeneratedKeysReturnNotSupportedException(Throwable t) {
        super(t);
    }

    public AutogeneratedKeysReturnNotSupportedException(String message) {
        super(message);
    }

    public AutogeneratedKeysReturnNotSupportedException() {
        super();
    }

}
